#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TerminalHelpTopic {
    Copy,
    Links,
    Images,
    Selection,
    Notifications,
    CliYoutube,
}

pub fn lines_for(topic: TerminalHelpTopic) -> Vec<String> {
    match topic {
        TerminalHelpTopic::Copy => copy_lines(),
        TerminalHelpTopic::Links => link_lines(),
        TerminalHelpTopic::Images => image_lines(),
        TerminalHelpTopic::Selection => selection_lines(),
        TerminalHelpTopic::Notifications => notification_lines(),
        TerminalHelpTopic::CliYoutube => cli_youtube_lines(),
    }
}

fn copy_lines() -> Vec<String> {
    [
        "Why copy sometimes silently fails",
        "",
        "When you press c on a chat message, late.sh emits OSC 52 - a standard",
        "escape sequence that asks the host terminal to put text on the system",
        "clipboard. The server has no other way to reach your clipboard over SSH;",
        "we hand the bytes to your terminal and hope it cooperates.",
        "",
        "Works out of the box",
        "  kitty, Ghostty, foot, wezterm, st, contour, zellij, hterm",
        "  rxvt-unicode (urxvt)",
        "  alacritty (default config writes to clipboard via OSC 52)",
        "  Windows Terminal (write only - it will not let apps read clipboard)",
        "  Konsole (recent versions; older Konsole had no OSC 52 support)",
        "",
        "Off by default - flip a setting first",
        "",
        "  iTerm2",
        "    Settings -> General -> Selection",
        "    -> turn on Applications in terminal may access clipboard",
        "    Without that toggle, copy looks like nothing happened.",
        "",
        "  xterm",
        "    OSC 52 is gated behind allowWindowOps, off by default.",
        "    Run with -xrm '*.allowWindowOps: true' or set it in .Xresources.",
        "",
        "Does not support OSC 52 at all",
        "",
        "  macOS Terminal.app - no support, switch to iTerm2/Ghostty/kitty",
        "  GNOME Terminal, Tilix, Terminator, XFCE Terminal - all VTE-based,",
        "    OSC 52 was rejected upstream as a security risk",
        "  GNU screen - drops the sequence",
        "  Mosh - drops the sequence; use plain ssh if clipboard matters",
        "",
        "tmux",
        "  tmux strips OSC 52 unless you opt in. Add to ~/.tmux.conf:",
        "    set -g set-clipboard on",
        "    set -ga terminal-overrides ',*:Ms=\\E]52;%p1%s;%p2%s\\007'",
        "  Reload with: tmux source ~/.tmux.conf",
        "",
        "How to tell if it worked",
        "  No banner means the bytes left late.sh successfully. Whether anything",
        "  landed on your clipboard is between your terminal and your OS.",
        "  Try pasting somewhere - that is the only real check.",
        "",
        "Workaround",
        "  Most messages are short. You can always select text with the mouse",
        "  the old-fashioned way and copy through your terminal's own menu.",
    ]
    .into_iter()
    .map(str::to_string)
    .collect()
}

fn link_lines() -> Vec<String> {
    [
        "Why links are not always clickable",
        "",
        "There is a fancier escape sequence (OSC 8) that wraps a span of text",
        "as a real hyperlink the terminal can open on click. late.sh does not",
        "emit it.",
        "",
        "Why we skipped OSC 8",
        "  - it overlays normal text, so it fights with selection, mouse",
        "    forwarding, and our own click handlers",
        "  - terminal support is uneven; on some terminals the link layer",
        "    swallows clicks meant for buttons or chat messages",
        "  - getting it right across kitty, Ghostty, iTerm2, wezterm, tmux,",
        "    and the various Linux terminals is a constant maintenance tax",
        "  - the URL is right there in the message - you can read it",
        "",
        "What works on most terminals",
        "  Plain URLs in chat are still detected by the terminal's own URL",
        "  scanner. The exact modifier varies:",
        "",
        "  kitty           Ctrl+Shift+click, or `kitty +open`",
        "  Ghostty         Cmd+click (mac) / Ctrl+click (linux)",
        "  iTerm2          Cmd+click",
        "  wezterm         Ctrl+Shift+click, or right-click -> Open link",
        "  alacritty       Ctrl+click (with mouse.url config)",
        "  GNOME Terminal  Ctrl+click",
        "  Konsole         Ctrl+click",
        "  Windows Terminal  Ctrl+click",
        "  foot            Ctrl+click, or t to enter URL mode",
        "",
        "Built-in copy",
        "  When a chat message has a URL, press c on it. late.sh extracts the",
        "  URL and sends it through the same OSC 52 path described in the Copy",
        "  tab. That works even on terminals that refuse to make the URL",
        "  clickable - assuming OSC 52 itself works (see Copy tab).",
        "",
        "Per-feature shortcuts",
        "  Showcase, Work, News, Feeds: Enter on a row copies the URL",
        "  News modal: Enter copies and closes",
        "",
        "If clicks just do not register",
        "  Your terminal may need mouse reporting enabled, or tmux may be",
        "  intercepting the click. Use the keyboard shortcut to copy the URL",
        "  and paste it into your browser instead.",
    ]
    .into_iter()
    .map(str::to_string)
    .collect()
}

fn image_lines() -> Vec<String> {
    [
        "How images work",
        "",
        "There are three ways to get an image into chat:",
        "",
        "  paste image bytes",
        "    Paste PNG/JPEG/GIF/WebP bytes directly into the chat composer.",
        "    This uses bracketed paste. If file storage is configured, late.sh",
        "    uploads the image and posts the resulting URL.",
        "",
        "  /upload <url>",
        "    Downloads a public http(s) PNG/JPEG/GIF/WebP URL and reuploads it",
        "    into late.sh file storage. Redirects, localhost, and private",
        "    network addresses are rejected.",
        "",
        "  /paste-image",
        "    Asks a paired native CLI to read your OS clipboard image and send",
        "    it back to the SSH session for upload. This is CLI-only: browser",
        "    pairing cannot read your clipboard image for SSH. If it says no",
        "    paired CLI supports clipboard images, update and run `late`.",
        "",
        "Upload limits",
        "  Supported types: PNG, JPEG, GIF, WebP.",
        "  Default max upload size is 10 MiB, configurable server-side.",
        "  Uploads are rate-limited, and only one image upload can run at once.",
        "  If file storage is disabled, all upload paths show an error.",
        "",
        "Image previews in chat",
        "  URLs ending in .jpg/.jpeg/.png/.gif/.webp are detected.",
        "  Known image hosts such as uguu.se, 0x0.st, and catbox.moe are also",
        "  detected even when the URL path does not expose an extension.",
        "  The message list renders a compact Chafa symbol preview.",
        "  Select an image message and press Enter to open the image modal.",
        "  In the modal, Enter or c copies the image URL; Esc/q closes it.",
        "",
        "Preview quality",
        "  The original-quality image is the uploaded/copied URL.",
        "  Terminal previews are scaled to fit the current terminal; they are",
        "  not full-resolution image viewers.",
        "  The inline chat preview is the most portable path, but it is a",
        "  lower-detail ANSI symbol rendering.",
        "  The modal can use native terminal image protocols for full-color",
        "  raster previews when the terminal supports them.",
        "",
        "Native terminal image support",
        "  Kitty protocol: kitty, Ghostty, rio, warp, Konsole.",
        "  iTerm2 inline images: iTerm2, WezTerm, mintty, hterm.",
        "  Sixel: Windows Terminal, foot, contour, mlterm, sixel terminals.",
        "  tmux/screen disable native terminal images in late.sh; use a direct",
        "  terminal session if you want the full-color modal preview.",
        "",
        "Troubleshooting",
        "  If preview is stuck on Loading, the URL may block server fetches or",
        "  exceed decode limits.",
        "  If the modal falls back to text blocks, native image protocol",
        "  detection failed or the terminal cannot draw that preview size.",
        "  If /paste-image fails, make sure the native CLI is paired on the",
        "  same session token and advertises clipboard_image support.",
    ]
    .into_iter()
    .map(str::to_string)
    .collect()
}

fn selection_lines() -> Vec<String> {
    [
        "Why selecting text is sometimes blocked",
        "",
        "late.sh enables mouse reporting so it can react to clicks, scroll",
        "wheels, and drags inside the TUI. Once mouse reporting is on, the",
        "terminal forwards mouse events to the app instead of doing its own",
        "selection - that is why click-and-drag often does nothing.",
        "",
        "How to force a real selection",
        "",
        "  kitty           hold Shift while dragging",
        "  Ghostty         hold Shift while dragging",
        "  iTerm2          hold Option (Alt) while dragging",
        "  wezterm         hold Shift while dragging",
        "  alacritty       hold Shift while dragging",
        "  GNOME Terminal  hold Shift while dragging",
        "  Konsole         hold Shift while dragging, or middle-click to paste",
        "  Windows Terminal  hold Shift while dragging",
        "  foot            hold Shift while dragging",
        "  xterm           hold Shift while dragging",
        "",
        "Rule of thumb: Shift+drag is the standard escape hatch. macOS",
        "terminals often use Option/Alt instead.",
        "",
        "tmux extra step",
        "  tmux runs its own selection layer on top. Either:",
        "    - hold Shift to bypass tmux entirely (uses the terminal's selection)",
        "    - or enter copy mode: prefix [ then move/select with vi keys",
        "  If you have set -g mouse on in tmux, Shift+drag is again the way",
        "  to bypass tmux's selection and use the terminal's.",
        "",
        "Why we keep mouse reporting on",
        "  Click-to-select messages, click-to-react, scroll-to-page, and the",
        "  Artboard cursor all need it. Disabling it would break more than it",
        "  fixes.",
        "",
        "Built-in alternatives",
        "  c on a chat message copies its content via OSC 52",
        "  c on rooms/news/feeds copies the relevant URL",
        "  s in Bonsai copies the bonsai art",
    ]
    .into_iter()
    .map(str::to_string)
    .collect()
}

fn notification_lines() -> Vec<String> {
    [
        "Why notifications sometimes do not show up",
        "",
        "Desktop notifications use OSC 777 (kitty/Ghostty/foot/wezterm/konsole)",
        "and OSC 9 (iTerm2). late.sh sends one or both based on Settings ->",
        "Notify Format. The terminal then decides whether to surface a system",
        "notification.",
        "",
        "What can swallow them",
        "  - tmux strips notification escape sequences by default",
        "  - some terminals show notifications only when unfocused",
        "  - macOS Focus modes block them at the OS level",
        "  - the bell character is muted in most modern terminals",
        "  - GNOME Terminal and other VTE-based terminals do not implement",
        "    OSC 777 / OSC 9 - the bytes are silently ignored",
        "",
        "tmux",
        "  Add to ~/.tmux.conf:",
        "    set -g allow-passthrough on",
        "  Or rely on tmux's own activity/bell monitoring instead.",
        "",
        "If nothing fires",
        "  Try switching Notify Format to the other option in Settings, then",
        "  test with a DM from another session. The Bell toggle is a separate",
        "  audible cue that some terminals also drop.",
    ]
    .into_iter()
    .map(str::to_string)
    .collect()
}

fn cli_youtube_lines() -> Vec<String> {
    [
        "CLI YouTube playback",
        "",
        "When you switch audio source to YouTube, the native CLI starts a",
        "small companion webview window unless you already have the browser",
        "connect page paired. That window hosts the official YouTube IFrame",
        "Player. The CLI still handles SSH, chat, queue controls, mute/volume",
        "keys, and Icecast playback.",
        "",
        "Why there is a separate window",
        "  YouTube playback has to happen in a browser engine. We do not shell",
        "  out to mpv, vlc, yt-dlp, or server-side fetching. The webview keeps",
        "  the official player, ads/branding, and YouTube's normal media path.",
        "",
        "Linux requirements",
        "  WebKitGTK 4.1 runtime",
        "  GStreamer playback plugins",
        "  On Arch/EndeavourOS:",
        "    sudo pacman -S --needed webkit2gtk-4.1 gst-plugins-good gst-libav",
        "",
        "NixOS",
        "  Prefer the flake package:",
        "    nix run github:mpiorowski/late-sh#late",
        "  It wraps the CLI with WebKitGTK, GStreamer plugin, and GIO TLS",
        "  paths. A random Linux binary is likely to miss those runtime paths.",
        "  If packaging yourself, include webkitgtk_4_1, glib-networking,",
        "  gstreamer.out, GStreamer plugins, and gst-libav. Avoid LV2 in",
        "  gst-plugins-bad if libgstlv2.so crashes while scanning plugins.",
        "  The wrapper must expose GST_PLUGIN_SYSTEM_PATH_1_0,",
        "  GST_PLUGIN_SCANNER, GIO_EXTRA_MODULES, and WebKit sandbox paths.",
        "  If the webview package is busted, open the normal browser connect",
        "  page; it takes over YouTube playback automatically.",
        "",
        "Wayland / Hyprland",
        "  The helper asks for an undecorated window. The window app id is",
        "  sh.late.youtube. Confirm the live class/title first:",
        "    hyprctl clients | grep -A25 -i late",
        "  Current Hyprland docs use match:class window rules:",
        "    windowrule = match:class sh.late.youtube, float on",
        "    windowrule = match:class sh.late.youtube, size 480 320",
        "    windowrule = match:class sh.late.youtube, center on",
        "  Scratchpad routing with the same syntax:",
        "    windowrule = match:class sh.late.youtube, workspace special:late silent",
        "    bind = SUPER, Y, togglespecialworkspace, late",
        "  Older configs may still need the legacy windowrulev2 form:",
        "    windowrulev2 = float, class:^(sh.late.youtube)$",
        "    windowrulev2 = size 480 320, class:^(sh.late.youtube)$",
        "    windowrulev2 = center, class:^(sh.late.youtube)$",
        "    windowrulev2 = workspace special:late silent, class:^(sh.late.youtube)$",
        "",
        "Common Linux symptoms",
        "  No window:",
        "    Check the webview helper log under $XDG_STATE_HOME/late/",
        "    webview.log or ~/.local/state/late/webview.log. A GTK",
        "    application-id panic or unsupported window handle means the",
        "    helper is failing before WebKit starts.",
        "",
        "  Segfault in libatk-bridge-2.0.so / repeated dbind-WARNING:",
        "    The host AT-SPI accessibility bus is wedged, often because stale",
        "    at-spi-bus-launcher processes are stuck. The normal CLI helper",
        "    opts out with NO_AT_BRIDGE=1, but direct spike tests may need:",
        "      NO_AT_BRIDGE=1 late webview-spike <video_id>",
        "    Restarting/killing stale at-spi-bus-launcher processes can also",
        "    clear the crash.",
        "",
        "  White/blank window:",
        "    Usually a WebKitGTK construction problem. The Wayland path must use",
        "    Wry's GTK builder and Tao's GTK vbox container.",
        "",
        "  YouTube error 153:",
        "    YouTube rejected the embed identity. The page must be served from",
        "    a loopback HTTP origin, not Wry's raw with_html/null-origin path.",
        "",
        "  Black window, status says unstarted:",
        "    Often missing GStreamer plugins. If the log says",
        "    'GStreamer element autoaudiosink not found', install",
        "    gst-plugins-good.",
        "",
        "  Video moves but no sound:",
        "    Press + to raise the webview volume, press m to toggle mute, or",
        "    click once inside the webview to satisfy an autoplay gesture.",
        "    Also check your desktop mixer for a WebKit/late.sh stream.",
        "",
        "  Plays through laptop speakers first:",
        "    PipeWire/WirePlumber may treat the webview as a new app stream.",
        "    Move it to headphones once in your mixer; the session manager",
        "    usually remembers the route after that.",
        "",
        "Other platforms",
        "  macOS: uses WKWebView. No GStreamer, but autoplay policy and normal",
        "    system audio routing still apply.",
        "  Windows: uses WebView2. Modern Windows usually has it installed;",
        "    the Windows volume mixer may show it as a separate app stream.",
        "  WSL/headless/container: not a supported target unless there is a",
        "    working desktop, webview runtime, and audio bridge.",
        "",
        "Operational notes",
        "  The helper starts only while your source is YouTube and no real",
        "  browser connect page is paired. Opening the browser connect page",
        "  takes over YouTube playback and closes the helper; closing the",
        "  browser lets the CLI helper act as fallback again.",
        "  Default webview volume is 30%, matching native CLI Icecast.",
        "  The helper log is the first place to look when it acts weird.",
    ]
    .into_iter()
    .map(str::to_string)
    .collect()
}
